// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;
using ObjectDetectionLearning;


// Create single instance of sample data from first line of dataset for model input.
var image = MLImage.CreateFromFile(@"TestImages/Bobr.jpg");
ObjectDetectionModel.ModelInput sampleData = new ObjectDetectionModel.ModelInput()
{
    Image = image,
};

// Make a single prediction on the sample data and print results.
var predictionResult = ObjectDetectionModel.Predict(sampleData);
Console.WriteLine("\n\nPredicted Boxes:\n");
if (predictionResult.PredictedBoundingBoxes == null)
{
    Console.WriteLine("No Predicted Bounding Boxes");
    return;
}
var boxes =
    predictionResult.PredictedBoundingBoxes.Chunk(4)
        .Select(x => new { XTop = x[0], YTop = x[1], XBottom = x[2], YBottom = x[3] })
        .Zip(predictionResult.Score, (a, b) => new { Box = a, Score = b });

var boxestwo = boxes.ToArray();

for (int i = 0; i < predictionResult.Labels.Length; i++)
{
    var item = boxestwo.ToArray()[i];
    var label = predictionResult.Labels[i];

    Console.WriteLine($"XTop: {item.Box.XTop},YTop: {item.Box.YTop},XBottom: {item.Box.XBottom},YBottom: {item.Box.YBottom}, Score: {item.Score},  Lable:{label}");
}

//TLAiTFiysCpJuG5ZTkqwditvvN12JQkC29